config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "urls/index"
  get "urls/show"
  get "urls/new"
  get "urls/create"
  get "urls/edit"
  get "urls/update"
  get "urls/destroy"
  get "users/new"
  get "users/create"
  get "users/show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "urls#index"
  resources :urls, only: [:index, :new, :create, :show, :edit, :update, :destroy], param: :short_url
  resources :users, only: [:new, :create, :show]

  get '/login', to: 'users#login', as: :login
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout
  get '/register', to: 'users#register', as: :register
  post '/register', to: 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/url.rb
class Url < ApplicationRecord
  belongs_to :user
  validates :long_url, presence: true
  validates :short_url, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :urls
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||=User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def require_login
    unless logged_in?
      redirect_to login_path, alert: 'You must log in to access this page!'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully!'
    else
      flash.now[:alert] = 'Invalid email or password'
      render :login
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: 'Logged out successfully!'
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  include ApplicationHelper

  before_action :require_login
  before_action :set_url, only: [:show, :edit, :update, :destroy]

  def index
    @urls = Url.all
  end

  def show
    @url = Url.find_by(short_url: params[:short_url])
    if @url.nil?
      redirect_to urls_path, alert: 'URL not found'
    end
  end
  
  def new
    @url = Url.new
  end
  
  def create
    @url = Url.new(url_params)
    @url.short_url = generate_random_string
    @url.user_id = current_user.id
    Rails.logger.debug("URL params: #{@url.inspect}")
    
    if @url.save
      redirect_to @url, notice: 'URL successfully created'
    else
      Rails.logger.error(@url.errors.full_messages.join(", "))
      render :new
    end
  end
  
  def edit
    render 'urls/show'
  end

  def update
    if @url.update(url_params)
      redirect_to @url, notice: 'URL successfully updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @url = Url.find_by(short_url: params[:short_url])

    if @url.nil?
      redirect_to urls_path, alert: 'URL not found'
    elsif @url.user_id != current_user.id
      redirect_to urls_path, alert: 'You are not authorized to delete this URL!'
    else
      @url.destroy
    redirect_to urls_path, notice: 'URL successfully deleted'
    end
  end

  private

  def set_url
    @url = Url.find_by(short_url: params[:short_url])
    unless @url
      redirect_to urls_path, alert: 'URL not found'
    end
  end

  def url_params
    params.require(:url).permit(:short_url, :long_url, :user_id)
  end

  def require_login
    unless logged_in?
      redirect_to login_path, alert: 'You must log in to access this page!'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
    render :login
  end

  def new
    @user = User.new
    render :register
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Welcome, #{@user.email}!"
    else
      flash.now[:alert] = 'There was a problem creating your account.'
      render :register
    end
  end

  def show
  end

  private
  
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def generate_random_string
    SecureRandom.urlsafe_base64(6)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark bg-success">
    <a class="navbar-brand" href="<%= urls_path %>">TinyApp on Rails</a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup"
      aria-expanded="false"
      aria-label="Toggle navigation" >
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav" >
        <a class="nav-item nav-link" href="<%= urls_path %>">My URLs</a>
        <a class="nav-item nav-link" href="<%= new_url_path %>">Create New URL</a>
        
        <% if current_user %>
          <span class="nav-item nav-link">
            Welcome, <%= current_user.email %>!
          </span>
          <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-warning form-inline" %>
        <% else %>
          <a class="nav-item nav-link" href="<%= new_user_path %>">Register</a>
          <a class="nav-item nav-link" href="<%= login_path %>">Login</a>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tinyapp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
    integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
    crossorigin="anonymous">

  <title>TinyApp</title>
</head>

<body>
  <%= render "layouts/header" %>

  <main style="margin: 1em;">
    <h3>My URLs</h3>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Short URL ID</th>
          <th scope="col">Long URL</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <% @urls.each do |url| %>
          <tr>
            <td>
              <a href="<%= url.long_url %>" target="_blank">
                <%= url.short_url %>
              </a>
            </td>
            <td>
              <a href="<%= url.long_url %>" target="_blank">
                <%= url.long_url %>
              </a>
            </td>
            <td>
              <% if current_user && current_user.id == url.user_id %>
                <a href="<%= url_path(url.short_url) %>">
                  <button class="btn btn-primary">Edit</button>
                </a>
              <% else %>
                <button class="btn btn-secondary" disabled>Not allowed</button>
              <% end %>
            </td>
            <td>
              <% if current_user && current_user.id == url.user_id %>
                <%= form_with url: url_path(url.short_url), method: :delete, local: true do %>
                  <button class="btn btn-danger" type="submit">Delete</button>
                <% end %>
              <% else %>
                <button class="btn btn-secondary" disabled>Not allowed</button>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </main>

  <!-- Bootstrap JS -->
  <script
    src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>
</html>

app/views/urls/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
    integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
    crossorigin="anonymous">

  <title>TinyApp</title>
</head>

<body>
  <%= render "layouts/header" %>

  <main style="margin: 1em;">
    <h3>Create TinyURL</h3>
    <%= form_with model: @url, local: true do |form| %>
    <div class="form-group mb-2">
      <%= form.label :long_url, "Enter a URL:" %>
      <%= form.text_field :long_url, placeholder: "http://", class: "form-control", style: "width: 300px; margin: 1em" %>
      <%= form.submit "Submit", class: "btn btn-primary" %>
    </div>
    <% end %>


  </main>

      <!-- Bootstrap JS -->
      <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous" ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous" ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous" ></script>
      
</body>
</html>

app/views/urls/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
    integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
    crossorigin="anonymous">

  <title>TinyApp</title>
</head>

<body>
  <%= render "layouts/header" %>

  <main style="margin: 1em;">
    <div class="card text-center">
      <div class="card-header"></div>
      <h1>Edit URL</h1>
      <div class="card-body">
        <h5 class="card-title">TinyURL for: <%= @url.long_url %></h5>
        <p class="card-text">
          Short URL ID: <a href="<%= url_path(@url.short_url) %>"><%= @url.short_url %></a>
        </p>
      </div>
      <% if current_user && current_user.id == @url.user_id %>
      <div class="card-footer text-muted">
        <%= form_with url: url_path(@url.short_url), method: :patch do %>
        <label for="longURL">New URL:</label>
        <%= text_field_tag :longURL, @url.long_url, class: "form-control", required: true %>
        <%= submit_tag "Submit", class: "btn btn-primary mt-2" %>
        <% end %>
      </div>
      <% else %>
      <div class="card-footer text-muted">
        <p class="text-danger">You do not have permission to edit this URL!</p>
      </div>
      <% end %>
    </div>
  </main>

  <!-- Bootstrap JS -->
  <script
    src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous" ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous" ></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous" ></script>
</body>
</html>

app/views/users/login.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
    integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
    crossorigin="anonymous">

  <title>TinyApp</title>
</head>

<body>
  <%= render "layouts/header" %>

  <main style="margin: 1em;">
    <h1>Login</h1>
    <%= form_with url: login_path, method: :post, local: true  do |form| %>
    <div class="form-group">
      <%= form.label :email, "Email: " %>
      <%= form.email_field :email, class: "form-control", placeholder: "email" %>
    </div>
    <div class="form-group">
      <%= form.label :password, "Password: " %>
      <%= form.password_field :password, class: "form-control", placeholder: "password" %>
    </div>
    <%= form.submit "Log in!", class: "btn btn-primary" %>
    <% end %>
  </main>

    <!-- Bootstrap JS -->
    <script
    src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous" ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous" ></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous" ></script>
</body>
</html>

app/views/users/register.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
    integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
    crossorigin="anonymous">

  <title>TinyApp</title>
</head>

<body>
  <%= render "layouts/header" %>
  
  <main style="margin: 1em;">
    <h1>Create Account</h1>
    <%= form_with model: @user, url: register_path, method: :post, local: true  do |form| %>
    <div class="form-group">
      <%= form.label :email, "Email: " %>
      <%= form.email_field :email, class: "form-control", placeholder: "email" %>
    </div>
    <div class="form-group">
      <%= form.label :password, "Password: " %>
      <%= form.password_field :password, class: "form-control", placeholder: "password" %>
    </div>
    <%= form.submit "Register!", class: "btn btn-primary" %>
    <% end %>
  </main>

    <!-- Bootstrap JS -->
    <script
    src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous" ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous" ></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous" ></script>
</body>
</html>